name: Deploy Node.js to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          HOST: "35.166.20.238"
          USER: "ubuntu"
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          # Create SSH key file
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Connect to EC2 and deploy
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            # Update system
            sudo apt update -y

            # Clone/update repository
            if [ ! -d "/home/ubuntu/andrew-uat" ]; then
              git clone git@github.com:prof-gautam/andrew-backend.git /home/ubuntu/andrew-uat
            fi
            cd /home/ubuntu/andrew-uat

            # Pull latest code
            git pull origin main

            # Install dependencies
            npm install

            # Start/Restart app
            pm2 restart andrew-uat || pm2 start server.js --name "andrew-uat"

            # Show status
            pm2 list
          EOF
