name: Deploy Node.js to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          HOST: "35.166.20.238"
          USER: "ubuntu"
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          # Create the SSH key file
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Connect to EC2 and deploy the application
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            # Step 1: Update & Prepare Server
            sudo apt update -y
            sudo apt install -y git nodejs npm

            # Step 2: Clone or Update Repo
            cd /home/ubuntu/andrew-uat || git clone git@github.com:prof-gautam/andrew-backend.git andrew-uat
            cd /home/ubuntu/andrew-uat

            # Step 3: Set Correct Permissions
            sudo chown -R ubuntu:ubuntu .

            # Step 4: Pull Latest Code
            git pull origin main

            # Step 5: Install Dependencies
            npm ci

            # Step 6: Run Linting
            npm run lint || echo "Linting failed, continuing deployment..."

            # Step 7: Start or Restart App
            pm2 restart andrew-uat || pm2 start server.js --name "andrew-uat"

            # Step 8: Verify Status
            pm2 list
          EOF
